change README
asuender/zusi3tcp_unix pull request #1
Opened 2020-12-15 15:21 UTC by asuender

changed README

2020-12-15 15:37 UTC, mfederczuk requested changes
Get yourself [markdownlint for VSCode](https://github.com/DavidAnson/vscode-markdownlint), and see what it says about the file.

2020-12-15 15:37 UTC, mfederczuk commented on README.md
>  ## Platforms
It is already explained that this repository is only for Unix-like systems, having this section is not necessary

2020-12-15 15:37 UTC, mfederczuk commented on README.md
> +This is a fork of [jonathanp0's](https://github.com/jonathanp0) [zusi3tcp](https://github.com/jonathanp0/zusi3tcp) repository. It works nearly the same as the orginal library. Some functions and clas
Leave the explanation of the repository in, otherwise it's needed to go to the parent repository for an explanation

2020-12-15 15:37 UTC, mfederczuk commented on README.md
> +**You should only use this library if you are use Unix-bases systems like Linux.** For Windows see the original repo.
"should" is the wrong word here, it **can't** be used on Windows NT systems, maybe change the sentence to something like: _"this is a port for Unix-like systems"_

2020-12-15 15:40 UTC, mfederczuk commented
You should also add your name to the license while you're at it

2020-12-16 15:55 UTC, mfederczuk requested changes

2020-12-16 15:55 UTC, mfederczuk commented on README.md
> +**This is a port for Unix-like systems.** For Windows see the original repo.
Even though on GitHub it says that you forked the repository, this isn't always clear (especially when the repository was locally cloned), so it's not completely possible to know what the original repository is.  
Maybe write something like "This is a port of [onathanp0/zusi3tcp](https://github.com/jonathanp0/zusi3tcp) for Unix-like systems, which originally only supported Windows systems."

2020-12-16 15:55 UTC, mfederczuk commented on README.md
> +coming soon
I don't really see a reason to keep these two sections with just the text "coming soon" - I'd just remove them altogether and add them back in when you actually have something to write here

2020-12-16 15:55 UTC, mfederczuk commented on README.md
> +# Zusi 3 TCP Protocol Library [Unix-like]
This is again just a nitpick and more subjective to me, but why are you using square brackets and not round parenthesis?

2020-12-16 16:03 UTC, asuender commented on README.md
> +# Zusi 3 TCP Protocol Library [Unix-like]
I use them in that heading because I think they fit here.

2020-12-16 16:06 UTC, mfederczuk commented on README.md
> +**This is a port for Unix-like systems.** For Windows see the original repo.
Did you forget to delete this line? This is pretty much the same sentence as the one you just added.

2020-12-16 16:08 UTC, asuender commented on README.md
> +**This is a port for Unix-like systems.** For Windows see the original repo.
Actually yes I forgot it.

2020-12-16 16:10 UTC, mfederczuk approved these changes

2020-12-17 19:32 UTC, merged